### ISSUE TITLE
Add Turkish

### ISSUE THREAD

**Issue by sweenu** [usemoslinux/aprelendo#192]
This software looks amazing! How hard is it to support new languages ? Could I help ?

**Comment by usemoslinux** [comment]
Hi!, we would be able to add support for Turkish. However, we would need someone to filter the frequency list table for that language. The one we would use as a base is the following: https://github.com/hermitdave/FrequencyWords/blob/master/content/2018/tr/tr_50k.txt

This list was created based on the Turkish subtitles from Open Subtitles and includes names of people and places (countries, cities, etc.) and other words of foreign origin, which would need to be filtered out.

If you think you could help us with this, let me know, so I can give you further hints.

**Comment by sweenu** [comment]
What and why do you need the frequency list ? If I find one that is already free from names of people and places, would that work ? That would probably be more easily achievable than filtering out manually 50k words. 
Anyways, glad to help though.

**Comment by usemoslinux** [comment]
Hi @sweenu,

Just a quick note to let you know that we've added preliminary support for Turkish and 13 additional languages. Chrome/Firefox/Edge extensions should be updated soon too.

If you enjoy using Aprelendo, please consider:

1. Supporting us through PayPal or Patreon. More info: https://www.aprelendo.com/donate.
2. Reporting any bugs or issues you encounter while using Aprelendo to learn Bulgarian or any other language.

Thank you!

**Comment by sweenu** [comment]
Awesome news, thanks!
