### ISSUE TITLE
Bulgarian 

### ISSUE THREAD

**Issue by VasilKotsov** [usemoslinux/aprelendo#193]
Can you please add Bulgarian language.
I really like the idea of that software.
Thank you.

**Comment by usemoslinux** [comment]
Thanks. Good to see you are enjoying Aprelendo!
We are going to bear that in mind for future updates.

**Comment by usemoslinux** [comment]
Hi @VasilKotsov,

Just a quick note to let you know that we've added preliminary support for Bulgarian and 13 additional languages. Chrome/Firefox/Edge extensions should be updated soon too.

If you enjoy using Aprelendo, please consider:

1. Supporting us through PayPal or Patreon. More info: https://www.aprelendo.com/donate.
2. Reporting any bugs or issues you encounter while using Aprelendo to learn Bulgarian or any other language.

Thank you!
